# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goread < Formula
  desc ""
  homepage "https://github.com/TypicalAM/homebrew-goread"
  version "1.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TypicalAM/goread/releases/download/v1.3.5/goread_Darwin_x86_64"
      sha256 "2fee24712932ae549b5f36abcdea2c8d98a1377e103f0ef7e0082a027606291f"

      def install
        bin.install "goread_Darwin_x86_64" => "goread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TypicalAM/goread/releases/download/v1.3.5/goread_Darwin_arm64"
      sha256 "3c25f00682f97e810ce2735be3ff233737b583f7a37376053094efddec7980c1"

      def install
        bin.install "goread_Darwin_arm64" => "goread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TypicalAM/goread/releases/download/v1.3.5/goread_Linux_arm64"
      sha256 "f4ced528284fe5b3b7f4d531b5f313930c5635833801fd07283d391074486eb8"

      def install
        bin.install "goread_Linux_arm64" => "goread"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TypicalAM/goread/releases/download/v1.3.5/goread_Linux_x86_64"
      sha256 "6a486f420d241a4141b3d54d3a81e259b9dfe4c166beab1e838cca015e24c8ab"

      def install
        bin.install "goread_Linux_x86_64" => "goread"
      end
    end
  end
end
