# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goread < Formula
  desc ""
  homepage "https://github.com/TypicalAM/homebrew-goread"
  version "1.6.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TypicalAM/goread/releases/download/v1.6.5/goread_Darwin_x86_64"
      sha256 "a11fbb88f90e8d7d6631071ab09c8bb9a18a71329756a83078b47f62428cd894"

      def install
        bin.install "goread_Darwin_x86_64" => "goread"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TypicalAM/goread/releases/download/v1.6.5/goread_Darwin_arm64"
      sha256 "da28c6a2aa50c563d4109e75a678473f42a0cfe906e6c5dd08366c0b7a018ac4"

      def install
        bin.install "goread_Darwin_arm64" => "goread"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/TypicalAM/goread/releases/download/v1.6.5/goread_Linux_x86_64"
      sha256 "8921b4bb2cdb0cc339699bedf477749b1e8e246b53e38e3007e27817c5dd2a2c"

      def install
        bin.install "goread_Linux_x86_64" => "goread"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TypicalAM/goread/releases/download/v1.6.5/goread_Linux_arm64"
      sha256 "6d92e32cd3fc93b7a765a9ea075c5b8d7c51aeb87227dae3c88a3c1c770ad6e9"

      def install
        bin.install "goread_Linux_arm64" => "goread"
      end
    end
  end
end
